apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: weather-app
  labels:
    app: weather-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      NodePort: 30003
  selector:
    app: weather-app